# Generated by Django 3.1.1 on 2020-09-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='accounts.Tag', verbose_name='Тег'),
        ),
    ]
